services:
  mongodb:
    image: mongo:7.0.14
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet mongodb://localhost:27017/admin --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    stop_grace_period: 30s

volumes:
  mongodb-data:
