services:
  mongodb:
    image: mongo:7.0.14
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    stop_grace_period: 30s

volumes:
  mongodb-data:
